DD-1459 Fix uncontrolled data used in path expression
DANS-KNAW/dd-ingest-flow pull request #132
Opened 2024-04-02 21:20 UTC by aliassheikh

Fixes DD-1459 Fix Uncontrolled data used in path expression

# Description of changes
  - Add `getSecurePath(Path path)` to `ImportArea.java`
  - Checking the trusted base folders of `dd-ingest-flow` in the classes`ImoprtResource` and `MigrationResource`

# How to test and follow it in debugger
  - Starting vagrant - open terminal and follow the instructions below :
    - `start-preprovisioned-box.py -s dev_archaeology`
    - `deploy.py  -m dd-ingest-flow dev_archaeology`
    - `vagrant ssh`
    - `cd /var/opt/dans.knaw.nl/tmp`
    - `tree -L 5` (to oversee the working folders and deposits)
    -  Create to test folders inside import and migration folders
      - `mkdir import/deposits/test-folder`
      - `mkdir migration/deposits/test-folder`
    - copy one of the deposits into new created test-folders
      - `cp -r auto-ingest/outbox/processed/33afaff6-e08a-4bfa-9960-2b48b616d2c9/ import/inbox/test-folder/` 
      - `cp -r auto-ingest/outbox/processed/33afaff6-e08a-4bfa-9960-2b48b616d2c9/ migration/deposits/test-folder/`
    - open dd-ingest-flow porject in IntelliJ and run remote-debug with info:
      - remote debug
      - host: dev.sword2.archaeology.datastations.nl
      - port: 20302 
    - Commands to import or migrate deposits:
      - `ingest-flow start-import -s import/inbox/test-folder/33afaff6-e08a-4bfa-9960-2b48b616d2c9/`
      - `ingest-flow start-migration -s migration/deposits/test-folder/33afaff6-e08a-4bfa-9960-2b48b616d2c9/`

# Related PRs

(Add links)

*

# Notify

@DANS-KNAW/core-systems

2024-04-05 12:27 UTC, jo-pol reviewed
Just some style details

2024-04-08 15:10 UTC, janvanmansum commented on src/main/java/nl/knaw/dans/ingest/resources/ImportsResource.java
> +            java.nio.file.Path securePath = importArea.getSecurePath(start.getInputPath());
I agree, let's use `var` here.

2024-04-08 15:10 UTC, janvanmansum commented on src/main/java/nl/knaw/dans/ingest/resources/MigrationsResource.java
> +            java.nio.file.Path securePath = migrationArea.getSecurePath(start.getInputPath());
I agree, let's use `var` here.

2024-04-08 15:10 UTC, janvanmansum requested changes
See inline comments.

2024-04-09 14:46 UTC, aliassheikh commented on src/main/java/nl/knaw/dans/ingest/resources/ImportsResource.java
> +            java.nio.file.Path securePath = importArea.getSecurePath(start.getInputPath());
in imports there is already a `Path` type (`import javax.ws.rs.Path;`)
In my case, it is `java.nio.file.Path`. I think it is clearer to have it.
But you asked and I am going to change it to `var`

2024-04-09 14:52 UTC, aliassheikh commented on src/main/java/nl/knaw/dans/ingest/resources/MigrationsResource.java
> +            java.nio.file.Path securePath = migrationArea.getSecurePath(start.getInputPath());
in imports there is already a `Path` type (`import javax.ws.rs.Path;`)
In my case, it is `java.nio.file.Path`. I think it is clearer to have it.
But you asked and I am going to change it to `var`

2024-04-11 06:12 UTC, janvanmansum commented on src/main/java/nl/knaw/dans/ingest/resources/ImportsResource.java
> +            java.nio.file.Path securePath = importArea.getSecurePath(start.getInputPath());
OK, I see your point. I prefer `var`, the function name `getSecurePath` already makes clear sufficiently what type of object is returned.

2024-04-11 06:13 UTC, merged